### ISSUE TITLE
fda-data-update

### ISSUE THREAD

**Issue by kenbr7613** [DrugLabelExplorer/dle#54]
Update
- Reduce Section Names with Map
- Better Product Names
- Stretch: Move Generics to list

**Comment by llandau** [comment]
I think we might want to have special behavior for the "SPL UNCLASSIFIED SECTION". I took a look at an FDA drug label and noticed that this section shows up 23 times in the single label.

If we see a `code.displayname = "SPL UNCLASSIFIED SECTION"` we might want to look for the following "title" and consider that the section_name.

Maybe something like:
```
                        if title == "SPL UNCLASSIFIED SECTION":
                            title = section.find_next("title")
```

**Comment by llandau** [comment]
Oh, I see now that if there is more than one section with the same section_name, the text is appended. So that's good.

**Comment by llandau** [comment]
FYI, I put a stab at parsing the unclassified section names here: https://github.com/DrugLabelExplorer/dle/commit/4bb9db821e2b866e8ef010987ec738533b2ae88f

**Comment by llandau** [comment]
We might want to have special handling for the other cases where there are more than one entry per label. Maybe we omit the "PACKAGE LABELPRINCIPAL DISPLAY PANEL". Also the "SPL PRODUCT DATA ELEMENTS SECTION" add up to more than one per label so we might want to ensure that's being handled properly.

**Comment by llandau** [comment]
I notice that text from the Indications and Usage section is being incorrectly added into 2 sections in the parsing in an example I am looking at. It is being included in the both the Indications and Usage Section along with being included in the "SPL UNCLASSIFIED SECTION". I randomly picked 667e493e-307b-4eb7-99e1-0939f25a7483.xml, which is https://druglabelexplorer.org/data/35341 in the db. The text "Piperacillin and tazobactam for injection is a combination of " is included twice on the page, but only shows up once in the xml file.

**Comment by llandau** [comment]
It looks like there are other instances of text being incorrectly added twice as well.

**Comment by llandau** [comment]
I figured out the bug for the duplicate text. There is a 'structuredBody' component that was causing all of the data to be included in the first section parsed.

Fix is:
```
                # the structuredbody component is the parent that contains everything, skip it
                structured_body = section.find_next("structuredbody")
                if structured_body is not None:
                    logger.debug(f"SKIPPING: structuredbody")
                    continue
```
